### ISSUE TITLE
 java.lang.IllegalStateException: subcompose can only be used inside the measure or layout blocks

### ISSUE THREAD

**Issue by razaghimahdi** [skydoves/Orbital#22]
App would crash if I use LazyRow or ScrollableTabRow or ... inside Orbital .
it says:
 java.lang.IllegalStateException: subcompose can only be used inside the measure or layout blocks .

how can I fix that?

**Comment by skydoves** [comment]
This issue happens in the latest version of Jetpack Compose. The LookAheadLayout doesn't support [SubComposeLayout](https://android-review.googlesource.com/c/platform/frameworks/support/+/2426772) now, so you should downgrade your Compose version to `1.3.1`.

**Comment by doris4lt** [comment]
The crash should be fixed in the next alpha release (i.e. 1.5.0-alpha02): https://android-review.git.corp.google.com/c/platform/frameworks/support/+/2426772

This changes requires an additional measure policy for SubcomposeLayouts. We'll be providing a custom intermediate measure policy for BoxWithConstraints and LazyList in the future. For now, the change linked above should fix any lookahead related crash. :)

**Comment by razaghimahdi** [comment]
> @razaghimahdi That's weird 🤔 Does the sample app works well on your side?

Hi, so sorry if it took to long to response, Yes I even tried the sample, and it didn't worked.

**Comment by razaghimahdi** [comment]
> The crash should be fixed in the next alpha release (i.e. 1.5.0-alpha02): https://android-review.git.corp.google.com/c/platform/frameworks/support/+/2426772
> 
> This changes requires an additional measure policy for SubcomposeLayouts. We'll be providing a custom intermediate measure policy for BoxWithConstraints and LazyList in the future. For now, the change linked above should fix any lookahead related crash. :)

Well I guess updating to 1.5.0-alpha02 isn't enough since this library would need some changes. Also thank u for ur time.

**Comment by skydoves** [comment]
Hey @razaghimahdi this issue has been fixed in the recent release. Thanks for the reporting!
